In [268]:
import pandas as pd

In [269]:
dataset = pd.read_csv('depression/survey.csv')

In [270]:
dataset.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [271]:
dataset.tail()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [272]:
dataset.columns

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [273]:
dataset.self_employed = dataset.self_employed.map({'No':0,'Yes':1})

In [274]:
dataset.drop(columns=['Timestamp'], inplace=True)

In [275]:
dataset.drop(columns=['Country'], inplace=True)

In [276]:
dataset.drop(columns=['state'], inplace=True)

In [277]:
dataset.drop(columns=['work_interfere'], inplace=True)

In [278]:
dataset.drop(columns=['no_employees'], inplace=True)

In [279]:
dataset.drop(columns=['benefits'], inplace=True)

In [280]:
dataset.drop(columns=['leave'], inplace=True)

In [281]:
dataset.drop(columns=['coworkers'], inplace=True)

In [282]:
dataset.drop(columns=['comments'], inplace=True)

In [283]:
dataset.drop(columns=['care_options'], inplace=True)

In [284]:
dataset.drop(columns=['self_employed'], inplace=True)

In [285]:
dataset.head()

,Age,Gender,family_history,treatment,remote_work,tech_company,wellness_program,seek_help,anonymity,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,No,Yes,No,Yes,No,Yes,Yes,No,No,Yes,No,Maybe,Yes,No
1,44,M,No,No,No,No,Don't know,Don't know,Don't know,Maybe,No,No,No,No,Don't know,No
2,32,Male,No,No,No,Yes,No,No,Don't know,No,No,Yes,Yes,Yes,No,No
3,31,Male,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Maybe,Maybe,No,Yes
4,31,Male,No,No,Yes,Yes,Don't know,Don't know,Don't know,No,No,Yes,Yes,Yes,Don't know,No

In [286]:
dataset.family_history = dataset.family_history.map({'No':0,'Yes':1})

In [287]:
dataset.Gender = dataset.Gender.map({'Male':0,'Female':1, 'male':0, 'female':1})

In [288]:
dataset.treatment = dataset.treatment.map({'No':0,'Yes':1})

In [289]:
dataset.remote_work = dataset.remote_work.map({'No':0,'Yes':1})

In [290]:
dataset.tech_company = dataset.tech_company.map({'No':0,'Yes':1})

In [291]:
dataset.wellness_program = dataset.wellness_program.map({'No':0,'Yes':1})

In [292]:
dataset.seek_help = dataset.seek_help.map({'No':0,'Yes':1})

In [293]:
dataset.anonymity = dataset.anonymity.map({'No':0,'Yes':1})

In [294]:
dataset.mental_health_consequence = dataset.mental_health_consequence.map({'No':0,'Yes':1})

In [295]:
dataset.phys_health_consequence = dataset.phys_health_consequence.map({'No':0,'Yes':1})

In [296]:
dataset.supervisor = dataset.supervisor.map({'No':0,'Yes':1})

In [297]:
dataset.mental_health_interview = dataset.mental_health_interview.map({'No':0,'Yes':1})

In [298]:
dataset.phys_health_interview = dataset.phys_health_interview.map({'No':0,'Yes':1})

In [299]:
dataset.mental_vs_physical = dataset.mental_vs_physical.map({'No':0,'Yes':1})

In [300]:
dataset.obs_consequence = dataset.obs_consequence.map({'No':0,'Yes':1})

In [301]:
dataset.head()

,Age,Gender,family_history,treatment,remote_work,tech_company,wellness_program,seek_help,anonymity,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,1.0,0,1,0,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,NaN,1.0,0
1,44,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0
2,32,0.0,0,0,0,1,0.0,0.0,NaN,0.0,0.0,1.0,1.0,1.0,0.0,0
3,31,0.0,1,1,0,1,0.0,0.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,1
4,31,0.0,0,0,1,1,NaN,NaN,NaN,0.0,0.0,1.0,1.0,1.0,NaN,0

In [302]:
dataset = dataset.dropna()

In [303]:
X = dataset[['Age','family_history','remote_work','tech_company','wellness_program','seek_help','anonymity','mental_health_consequence','phys_health_consequence','supervisor','mental_health_interview','phys_health_interview','mental_vs_physical','obs_consequence']]

In [304]:
X

,Age,family_history,remote_work,tech_company,wellness_program,seek_help,anonymity,mental_health_consequence,phys_health_consequence,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
45,38,1,0,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
90,31,0,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
91,40,0,0,1,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0
112,45,1,1,1,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
147,23,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0
210,40,0,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
237,34,1,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1
239,28,1,0,0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1
272,30,0,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
290,30,0,0,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
303,28,1,1,0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0
351,27,0,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0
363,32,1,0,0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0
383,25,1,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0
420,28,1,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
470,31,0,1,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
487,30,1,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
513,39,0,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
514,38,1,0,1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0
541,31,1,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
573,26,1,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1
578,29,0,1,1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0
584,27,0,1,1,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0
602,33,1,0,0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0
638,35,0,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
678,29,0,0,1,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
686,33,1,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
695,32,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
721,30,1,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1
727,30,1,0,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0
748,35,1,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
760,31,1,1,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
763,38,1,0,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0
803,30,0,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
817,44,1,1,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0
829,35,1,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
832,29,0,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
836,24,1,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1
856,51,0,1,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
888,26,0,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
896,33,0,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
945,39,1,0,1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0
955,33,1,0,1,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
961,25,0,1,1,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
971,30,0,0,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1
973,49,1,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
987,28,0,0,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0
1033,31,1,0,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1
1094,37,0,0,1,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1095,36,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1120,32,0,0,1,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1
1144,23,0,0,0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0
1232,25,1,0,0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0
1255,32,1,1,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0

In [305]:
y=dataset['treatment']

In [306]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

In [307]:
clf1 = RandomForestClassifier(n_estimators = 100)
clf2 = KNeighborsClassifier(n_neighbors=5)
clf3 = DecisionTreeClassifier(random_state=42)

In [308]:
voting_clf = VotingClassifier(estimators=[('rf', clf1), ('knn', clf2), ('dt', clf3)], voting='soft')

In [309]:
X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=42)

In [310]:
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier()),
                             ('knn', KNeighborsClassifier()),
                             ('dt', DecisionTreeClassifier(random_state=42))],
                 voting='soft')

In [311]:
y_pred = voting_clf.predict(X_test)

In [312]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7857142857142857